/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorAlumnos;
import Controlador.ControllerUser;
import Controlador.ControllerValidacines;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author tariq
 */
public class CreateStudent extends javax.swing.JFrame {

    /**
     * Creates new form CreateStudent
     */
    ControladorAlumnos objal = new ControladorAlumnos();
    ControllerUser objus = new ControllerUser();
    int i = 0;
    
    public CreateStudent() {
        initComponents();
        cmb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        aceptar = new javax.swing.JButton();
        nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        apeliido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        carnetest = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        year = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        especialidad = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        grupo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        seccion = new javax.swing.JComboBox<>();
        cancelar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Modalidad = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        Docente = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombres:");

        aceptar.setText("Aceptar");
        aceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aceptarMouseClicked(evt);
            }
        });

        jLabel2.setText("Apellidos:");

        apeliido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apeliidoActionPerformed(evt);
            }
        });

        jLabel3.setText("carnet:");

        jLabel4.setText("Año:");

        year.setText("YYYY/MM/DD");
        year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearActionPerformed(evt);
            }
        });

        jLabel5.setText("Especialidad");

        especialidad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                especialidadItemStateChanged(evt);
            }
        });

        jLabel6.setText("Grupo:");

        jLabel7.setText("Seccion: ");

        cancelar.setText("Cancelar");
        cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarMouseClicked(evt);
            }
        });

        jLabel8.setText("Modalidad");

        jLabel9.setText("Docente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(Docente, 0, 177, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addGap(18, 18, 18))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(33, 33, 33)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(nombre)
                                        .addComponent(carnetest, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(especialidad, 0, 158, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(seccion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(apeliido)
                                    .addComponent(year, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                    .addComponent(grupo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(Modalidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(apeliido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(carnetest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(especialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(grupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(seccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(Modalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Docente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(aceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void apeliidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apeliidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apeliidoActionPerformed

    private void yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearActionPerformed

    private void cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarMouseClicked
        // TODO add your handling code here:
        AddStudents open = new AddStudents();
        open.setVisible(true);
        dispose();
    }//GEN-LAST:event_cancelarMouseClicked

    private void aceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aceptarMouseClicked
        // TODO add your handling code here:
        CreateUser();
        CreateStdnt();
        if (i == 1) {
            JOptionPane.showMessageDialog(null, "Error al enviar el estudiante, revise su conexion", "Error de conexion", JOptionPane.ERROR_MESSAGE);
        }else if(i == 0){
            JOptionPane.showMessageDialog(null, "Error al enviar el usuario, revise su conexion", "Error de conexion", JOptionPane.ERROR_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "Se han subido el alumno exitosamente", "Proceso Compelto", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_aceptarMouseClicked

    private void especialidadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_especialidadItemStateChanged
        // TODO add your handling code here:
        objal.especialidad = especialidad.getSelectedIndex() + 1;
        try {
            Docente.removeAllItems();
            ResultSet rs = objal.MostraeDocenteFiltro();
            while (rs.next()) {                
                
                Docente.addItem(rs.getString("docente"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al cargar los filtros de especialidades, revise su conexion", "Error de conexion", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_especialidadItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateStudent().setVisible(true);
            }
        });
    }

    public void cmb(){
        try {
            ResultSet rs = objal.MostrarEspecialidad();
            while (rs.next()) {                
                especialidad.addItem(rs.getString("especialidad"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al cargar las especialidades, revise su conexion", "Error de conexion", JOptionPane.ERROR_MESSAGE);
        }
        try {
            ResultSet rs = objal.MostrarGrupo();
            while (rs.next()) {                
                grupo.addItem(rs.getString("grupo"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al cargar los grupos, revise su conexion", "Error de conexion", JOptionPane.ERROR_MESSAGE);            
        }
        try {
            ResultSet rs = objal.MostrarSeccion();
            while (rs.next()) {                
                seccion.addItem(rs.getString("seccion"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al cargar las secciones, revise su conexion", "Error de conexion", JOptionPane.ERROR_MESSAGE);

        }
        try {
            ResultSet rs = objal.MostrarDocente();
            while (rs.next()) {                
                Docente.addItem(rs.getString("docente"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al cargar los docentes, revise su conexion", "Error de conexion", JOptionPane.ERROR_MESSAGE);

        }
        try {
            ResultSet rs = objal.MostrarModalidad();
            while (rs.next()) {                
                Modalidad.addItem(rs.getString("modalidad"));
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al cargar las modalidades, revise su conexion", "Error de conexion", JOptionPane.ERROR_MESSAGE);

        }
    }
    
    boolean Empty(){
        if (nombre.getText().trim().equals("") || apeliido.getText().trim().equals("") || carnetest.getText().trim().equals("") || year.getText().trim().equals("YYYY/MM/DD")) {
            return false;
        }else{
            return true;
        }        
    }
    
    void CreateUser(){
        if (Empty() == true) {
            objus.usuario = carnetest.getText();
            objus.clave = ControllerValidacines.getMD5(carnetest.getText() + "PU123") ;
            objus.tipo = 1;
            objus.estado = 1;
            objus.intento = 0;
            int valor = objus.AgregarUsuario();
            if (valor == 1) {
                i++;
            }            
        }else{
            JOptionPane.showMessageDialog(null, "Existen capos vacios, por favor complete toda la informacion requerida", "Informacion Incompleta", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    void CreateStdnt(){
        int rs = objal.ObtenerUsuario(carnetest.getText());
        if (Empty() == true) {
            objal.nombre = nombre.getText();
            objal.apellido = apeliido.getText();
            objal.carnet = carnetest.getText();
            objal.modalidad = Modalidad.getSelectedIndex() + 1;
            objal.especialidad = especialidad.getSelectedIndex() + 1;
            objal.grupo = grupo.getSelectedIndex() + 1;
            objal.seccion = seccion.getSelectedIndex() + 1;
            objal.empresa = 0;
            objal.estado = 1;
            objal.usuario = rs;
            objal.docente = Docente.getSelectedIndex() + 1;
            objal.year = year.getText();
            int valor = objal.IngresarAlumno();
            if (valor == 1) {
                i++;
            }    
        }else{
            JOptionPane.showMessageDialog(null, "Existen capos vacios, por favor complete toda la informacion requerida", "Informacion Incompleta", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Docente;
    private javax.swing.JComboBox<String> Modalidad;
    private javax.swing.JButton aceptar;
    private javax.swing.JTextField apeliido;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField carnetest;
    private javax.swing.JComboBox<String> especialidad;
    private javax.swing.JComboBox<String> grupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nombre;
    private javax.swing.JComboBox<String> seccion;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
