/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorEmpresa;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marav
 */
public class NuevaEmpresa extends javax.swing.JFrame {

    /**
     * Creates new form NuevaEmpresa
     */
    DefaultTableModel modelo;
    public NuevaEmpresa() {
        initComponents();
        setLocationRelativeTo(null);
        LlenarCombobox();
        txturl.setVisible(false);
    }
    ControladorEmpresa obj = new ControladorEmpresa();
    void LlenarCombobox(){
        try {
            ResultSet rs = obj.CagarEstados();
            while (rs.next()) {
               cmbEstado.addItem(rs.getString("estado"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error, no se pudieron cargar los estados de empresa");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton4 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txturl = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtNombreEmp = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtDireccion = new javax.swing.JTextArea();
        btnAgregarLogo = new javax.swing.JButton();
        lbLogo = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        txtRepresentante = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, -1));

        jButton4.setBackground(new java.awt.Color(196, 152, 0));
        jButton4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Regresar");
        jButton4.setBorderPainted(false);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("ingrese la direccion de la sede central]");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 270, 20));

        txturl.setEditable(false);
        txturl.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txturl.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txturl, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 180, -1));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Nombre de la empresa");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 150, 20));

        txtNombreEmp.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtNombreEmp.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtNombreEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 300, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Numero tributario ");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 150, 20));

        txtNumero.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtNumero.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 300, -1));

        jLabel19.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Nombre completo del representante legal");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 270, 20));

        jLabel20.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Estado");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 40, 20));

        txtDireccion.setColumns(20);
        txtDireccion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtDireccion.setRows(5);
        jScrollPane5.setViewportView(txtDireccion);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 300, 90));

        btnAgregarLogo.setBackground(new java.awt.Color(196, 152, 0));
        btnAgregarLogo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAgregarLogo.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarLogo.setText("Agregar Logo");
        btnAgregarLogo.setBorderPainted(false);
        btnAgregarLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarLogoActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 130, -1));

        lbLogo.setBackground(new java.awt.Color(255, 255, 255));
        lbLogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(lbLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 180, 170));

        jLabel21.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Direccion [si posee muchos establecimientos");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 290, 20));

        jPanel1.add(cmbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 170, -1));

        jButton6.setBackground(new java.awt.Color(196, 152, 0));
        jButton6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Agregar");
        jButton6.setBorderPainted(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, -1, -1));

        txtRepresentante.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtRepresentante.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtRepresentante, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 300, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        Home abrir = new Home();
        abrir.setVisible(true);

        dispose();
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    String url;
    private void btnAgregarLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarLogoActionPerformed
        // TODO add your handling code here:
        //CARGANDO IMAGEN AL SISTEMA
        JFileChooser j = new JFileChooser();
        FileNameExtensionFilter fil = new FileNameExtensionFilter("JPG, PNG & GIF","jpg","png","gif");
        j.setFileFilter(fil);

        int s = j.showOpenDialog(this);
        if(s == JFileChooser.APPROVE_OPTION){
            String ruta = j.getSelectedFile().getAbsolutePath();
            txturl.setText(ruta);
            rsscalelabel.RSScaleLabel.setScaleLabel(lbLogo, ruta);

        }
    }//GEN-LAST:event_btnAgregarLogoActionPerformed

    void cargarTabala(){
        
    }
    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        AgregarEmpresa();
        
    }//GEN-LAST:event_jButton6ActionPerformed

    void AgregarEmpresa(){
        obj.nombre = txtNombreEmp.getText();
        obj.NumTributario = Integer.parseInt(txtNumero.getText());
        obj.Representante = txtRepresentante.getText();
        obj.estado = cmbEstado.getSelectedIndex() + 1;
        obj.Direccion = txtDireccion.getText();
        //Conversion de imagen a byte
        File ruta = new File(txturl.getText());
        try {
            byte [] imagen = new byte [(int) ruta.length()];
            InputStream input = new FileInputStream(ruta);
            input.read(imagen);
            obj.Logo = imagen;
            JOptionPane.showMessageDialog(null, "Imagen paso con exito" + imagen);

            if (obj.InsertarEmpresa() == true) {
                JOptionPane.showMessageDialog(null,"Empresa agregada exitosamente");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se pudo pasar la imagen");
            obj.Logo = null;
            if (obj.InsertarEmpresa() == true) {
                JOptionPane.showMessageDialog(null,"Empresa agregada exitosamente");
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevaEmpresa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarLogo;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JTextArea txtDireccion;
    private javax.swing.JTextField txtNombreEmp;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRepresentante;
    private javax.swing.JTextField txturl;
    // End of variables declaration//GEN-END:variables
}
